"""initial_migration

Revision ID: 70ce8c99375c
Revises: 20acb880199a
Create Date: 2025-12-15 21:29:43.304886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ce8c99375c'
down_revision: Union[str, Sequence[str], None] = '20acb880199a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('products', 'quanitity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quanitity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###
